### ISSUE TITLE
Sass Mixin for EQCSS

### ISSUE THREAD

**Issue by JawsomeJason** [eqcss/eqcss#35]
I _absolutely love_ this module, and I'll be using this everywhere from now on.

After taking a page from https://github.com/eqcss/eqcss/issues/26, I have added a gist with [a Sass mixin for EQCSS](https://gist.github.com/thejase/d2107285b6e10315dd6bc055115647fe) code.  There's an example in the gist of usage:

``` scss
// Make .foo background red when element width is larger than 500px and has 2 or more children
.foo {
  @include element((min-width: 500px), (min-children: 2)) {
    eq_this {
      background: red;
    }
  }
}
```

This allows Sass users to optionally skip the selector argument, instead using the current Sass scope.

Please feel free to use this in your README or link to it if you get a lot of questions/need.
