### ISSUE TITLE
Multiple element containers using the same class

### ISSUE THREAD

**Issue by scooterlord** [eqcss/eqcss#46]
Hello, it's me again! :)

So, here is an issue I just encountered. I am using the same element query in two containers of different widths. The queries are not applied properly, but are rather triggered when the condition is met at the larger container width.

Here is a fiddle with the issue:
https://jsfiddle.net/tLg0wh54/2/

**Comment by tomhodgins** [comment]
Hi @scooterlord! I see the demo and what's happening, the issue here might be a scoping issue!

When you create an element query, like so:

```css
@element 'div' {}
```

We would call the `div` here the ”scoped element”, or the element in the scope. As far as this query is concerned, the scoped element is a new point of reference in the same way that the HTML element is the single root element for the DOM and regular CSS.

Once we have an element scoped like this, we can use selectors like `$parent`, because from the reference point of a `div` that would refer to its parent element. If we use the `$prev` selector, it will select the element directly above/before the `div` in your HTML. The selector you need to use here is `$this`, which represents the scoped element that matches the query.

If you write:

```css
  @element ".widget-container" and (max-width:767px) {
    .widget {
      width:100%;
    }
  }
```

In english I would describe this as:

> When any element with a class of `widget-container` is no larger than `767px`, make all elements with a class of `widget` in the document `100%` wide.

In your case, this does match what you want - but it is making _all_ `.widget` elements on the page that width at the same time. Later on you write:

```css
@element ".widget-container" and (min-width:768px) and (max-width:991px) {
  .widget {
    width:50%;
  }
}
```

This I would describe as:

> When any element with a class of `widget-container` has at least a minimum with of `768px` and a is no wider than `991px`, make _all_ elements with a class of `widget` `50%` wide.

This is likely not what you intended to do. If you were using a unique ID this would work:

```css
@element "#example" and (min-width:768px) and (max-width:991px) {
  #example .widget {
    width:50%;
  }
}
```

> When the element with the ID of `example` has at least a minimum with of `768px` and is no wider than `991px`, make _all_ elements with a class of `widget` _inside_ `#example` to be `50%` wide.

That's sort of the specificity `$this` gives us for free, but without the need for unique IDs, here's an example that should work:

```css
@element ".widget-container" and (min-width:768px) and (max-width:991px) {
  $this .widget {
    width:50%;
  }
}
```

> When the element with the class of `widget-container` has at least a minimum with of `768px` and a is no wider than `991px`, make _all_ elements with a class of `widget` _inside the `.widget-container` element that matches this condition_ to be `50%` wide.

Here are some other examples to help explain the difference.

```css
@element 'div' and (min-width: 500px) {

  $this { background: red }
  /* when any div is <500px make it red itself */

  div { background: lime }
  /* when any div is <500px wide this makes ALL divs on the page lime  */

  $this div { background: gold }
  /* when any div is <500px wide make ALL divs inside matching div gold  */

}
```

I've gone in an prefaced each of the rules inside the element queries in your demo with `$this` so that the styles inside don't apply globally to all `.widget` elements on the page, but rather only those found within the scoped element: https://jsfiddle.net/tLg0wh54/3/

For another (similar) demo, check out: http://codepen.io/tomhodgins/pen/beeQON

If you remove `$this` from my demo you'll notice how the queries no longer work together, but set styles globally all over the same elements.

Also feel free to chat with us about EQCSS as you're using it on Gitter: https://gitter.im/eqcss/eqcss

Let me know if this solves what you're after, and happy hacking! ^_^
