### ISSUE TITLE
use $parent height in a rule?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [eqcss/eqcss#55]
Is there currently a way with EQCSS to use the dimensions of the parent node in calculations? eg something like this:
```css
@element '.item' {
  $this {
    height: eval('parent.height*2');
  }
}
```
