### ISSUE TITLE
eval() and SCSS

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [eqcss/eqcss#62]
if i use SCSS in this codepen - https://codepen.io/tomhodgins/pen/OpNWPg (obviously replacing `$this` with `eq_this`) i get an error

```scss
@element 'body' {
  eq_this {
    margin: 0;
    background: #222;
    eval('count = 0') // Invalid CSS after "...al('count = 0')": expected "{", was "}"
  }
}
```
is there a way i can use evals() in the way they are used in this codepen when using SCSS?
