### ISSUE TITLE
Write a postcss plugin that'd make this compatible with CSS modules

### ISSUE THREAD

**Issue by gajus** [eqcss/eqcss#70]
A large portion of user base is excluded because there is no integration with CSS modules.

The actual plugin is not complicated. All it needs to do is:

1. find `@element ".myDiv" and (min-width: 300px) {`
2. parse it
3. use https://github.com/css-modules/postcss-modules to generate a new name (see [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) for an example)
4. write `@element ".generatedClassName" and (min-width: 300px) {`

This issue has been raised with postcss team (https://github.com/css-modules/css-modules/issues/169). However, no one has picked it up since. Presumably, because there is lack of overlapping userbase between the two communities.

**Comment by gajus** [comment]
I want to elaborate on how this is integrates into a project. Just so that we are all on the same page.

Lets start with a typical CSS module setup.

I have my styles, e.g.

```css
.nose {
  color: red;
}

.sky {
  color: blue;
}

```

I consume these styles using a really awesome plugin [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules), e.g.

```js
import React from 'react';
import './styles.css';

export default () => {
  return <div styleName='sky'>
    <div styleName='nose'></div>
  </div>;
};

```

Two things happen when this project is built:

1. styles are assigned hashed named
2. markup is generated using `styleName` hashed result for `class` property

```html
<style>
.nose_demo_j4jf {
  color: red;
}

.sky_demo_14dg {
  color: blue;
}
</style>

<div class='sky_demo_14dg'>
  <div class='nose_demo_j4jf'></div>
</div

```

> Note that in a project that is consuming CSS modules, it is canonical to have 1-to-1 relation between a styleName and an element with a specific role.

Now, I want my "nose" to change color depending on the size of they "sky". I can do this using EQCSS.

```css
@element ".sky" and (min-width: 300px) {
  .nose {
    color: purple;
  }
}

```

For this to work, we need a postcss plugin that'd render the following CSS output:

```css
.nose_demo_j4jf {
  color: red;
}

.sky_demo_14dg {
  color: blue;
}

@element ".sky_demo_14dg" and (min-width: 300px) {
  .nose_demo_j4jf {
    color: purple;
  }
}

```

This way EQCSS is able to recognize the target element.
