### ISSUE TITLE
NPM package build not behaving the same as the CDN version

### ISSUE THREAD

**Issue by lmartins** [eqcss/eqcss#98]
Hi, I’m trying to use the library by including on my Webpack build, which uses SASS for css, but for some reason I’m not being able to get it to work with that setup.

When I instantiate EQCSS in JS like this:
```js
const ElementQueries = require('css-element-queries/src/ElementQueries');
ElementQueries.listen();
```
It will only work if my CSS rules look like this:

```scss
.parent{
  &[min-width~='400px'] {
    opacity: 1;
    grid-template-columns: 1fr 1fr;
  }
}
```

If however I use the utility helpers for SCSS that I’ve also included on the project, nothing happens:
```scss
.parent{
   @include element(
       (
         min-width: 400px
       )
     ) {
       eq_this {
         opacity: 1;
         grid-template-columns: 1fr 1fr;
       }
     }
   }
```
I’ve noticed that in this scenario, the generated CSS looks like this:
```css
/**/'@element '.parent' and (min-width: 400px) {/**/
  eq_this {
    opacity: 1;
    grid-template-columns: 1fr 1fr; }

/**/}'/**/
```
Am I missing a step here?
